export interface BlogPost {
  slug: string;
  category: string;
  title: string;
  excerpt: string;
  readTime: string;
  date: string;
  image: string;
  content: string;
  tags: string[];
}

export const posts: BlogPost[] = [
  {
    slug: "can-ayurveda-reduce-creatinine",
    category: "KIDNEY HEALTH",
    title: "Can Ayurveda Reduce Creatinine Levels? What the Evidence Says",
    excerpt:
      "Rising creatinine is the most common signal of kidney deterioration. Here is what Ayurveda actually does to address it — and what to expect.",
    readTime: "6 min read",
    date: "April 2025",
    image:
      "https://images.unsplash.com/photo-1628595351029-c2bf17511435?w=800&auto=format&fit=crop&q=80",
    tags: ["Kidney", "CKD", "Creatinine", "Ayurveda"],
    content: `
## What is Creatinine and Why Does it Rise?

Creatinine is a waste product generated by muscle metabolism. Healthy kidneys filter it out. When creatinine accumulates in the blood, it signals that the kidneys' filtration capacity — the GFR — has declined.

Normal creatinine is 0.6–1.2 mg/dL for men, 0.5–1.1 mg/dL for women. When it rises above these levels consistently, the diagnosis moves toward Chronic Kidney Disease (CKD).

## How Ayurveda Addresses the Root Cause

In Ayurveda, CKD is understood through the lens of **Mutravaha Srotas** — the channels governing urinary function. The accumulation of Ama (metabolic toxins) blocks these channels, impairing filtration and excretion.

Our protocol addresses this through three pathways:

**1. Herbal nephroprotection**
Specific formulations — Gokshura, Punarnava, Varuna, Shilajit — are clinically validated for their nephroprotective and diuretic properties. They reduce tubular inflammation, support glomerular repair, and improve filtration at the cellular level.

**2. Dietary correction**
A kidney-specific diet eliminates high-potassium, high-phosphorus, and high-protein foods that burden the filtering units. This alone can stabilise creatinine within 4–6 weeks in many patients.

**3. Panchkarma detox**
Basti (medicated enemas) and Virechana (therapeutic purgation) clear systemic Ama that compounds kidney deterioration. This is the detox layer that most herbal-only protocols miss.

## What Outcomes Are Realistic?

At our clinic, across documented cases:
- **68%** of CKD patients showed measurable creatinine reduction within 12 weeks
- **85%** avoided dialysis within our care program
- Most meaningful results appear between weeks 6 and 16 of consistent treatment

The stage of CKD matters significantly. Stage 1–3 patients consistently show better reversal potential than Stage 4–5.

## What Ayurveda Cannot Do

Ayurveda cannot reverse complete structural kidney damage. Fibrosed or non-functional nephrons do not regenerate. What we can do is halt progression, reduce the inflammatory burden, and meaningfully improve function in tissue that still has capacity.

## The Honest Conversation

If your creatinine is rising and dialysis is being recommended, Ayurveda is not a last resort — it works best when started early. But even late-stage patients have experienced stabilisation and improved quality of life under our protocols.

The question to ask is not "will it work" but "what is driving my creatinine rise" — and that is where Ayurvedic diagnosis excels.
    `,
  },
  {
    slug: "panchkarma-explained",
    category: "PANCHKARMA",
    title: "Panchkarma Explained: What Happens in a 21-Day Detox Program",
    excerpt:
      "Panchkarma is not a spa treatment. It is a systematic cellular detoxification developed over 3,000 years. Here is exactly what happens, day by day.",
    readTime: "8 min read",
    date: "March 2025",
    image:
      "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800&auto=format&fit=crop&q=80",
    tags: ["Panchkarma", "Detox", "Ayurveda", "Rejuvenation"],
    content: `
## What Panchkarma Actually Is

Panchkarma translates literally to "five actions" — the five classical purification therapies of Ayurveda. It is not a wellness retreat or a relaxation program. It is a medically supervised, systematic detoxification that clears accumulated toxins (Ama) from every tissue of the body.

The five therapies are:
1. **Vamana** — Therapeutic emesis (for Kapha disorders)
2. **Virechana** — Therapeutic purgation (for Pitta disorders)
3. **Basti** — Medicated enemas (for Vata disorders — the most powerful)
4. **Nasya** — Nasal administration (for head and neck conditions)
5. **Raktamokshana** — Blood purification (for skin and inflammatory conditions)

Not all five are administered to every patient. The selection depends on your Prakriti (constitution), Vikriti (current imbalance), and clinical presentation.

## The Three Stages of Our 21-Day Program

### Stage 1: Purva Karma (Days 1–7) — Preparation

Before purification begins, the body must be prepared. Ama that has lodged in deep tissues must be loosened and mobilised toward the digestive channels for elimination.

This involves:
- **Snehana** (oleation) — internal ghee administration in increasing doses, and external medicated oil massage
- **Svedana** (sweating) — herbal steam therapy to dilate channels and mobilise toxins

Most patients report feeling unusually warm, slightly nauseous, and heavy during this stage — a sign that Ama is moving.

### Stage 2: Pradhana Karma (Days 8–17) — Purification

The active purification therapies are administered based on your assessment:

- **Abhyanga + Pinda Sweda** — daily synchronised oil massage followed by herbal bolus heat therapy. Deeply therapeutic for joint, muscle, and neurological conditions.
- **Shirodhara** — continuous stream of medicated oil poured over the forehead. Profoundly calming. Used for stress, insomnia, anxiety, and neurological conditions.
- **Virechana** — on the appropriate day, therapeutic purgation clears Pitta toxins from the liver, blood, and small intestine.
- **Basti** — a course of medicated enemas over 8 days. Anuvasana (oil-based) alternated with Niruha (decoction-based). The single most powerful Ayurvedic therapy for Vata-dominant conditions.

### Stage 3: Paschat Karma (Days 18–21) — Restoration

After purification, the body is in a receptive, clean state. Rasayana (rejuvenation) herbs are introduced. Diet is gradually expanded. The body is rebuilt from the cleared foundation.

## What Patients Report

Most patients describe three distinct phases:
1. Days 1–5: Fatigue and heaviness as toxins mobilise
2. Days 8–14: A turning point — lightness, clarity, better sleep
3. Days 18–21: Energy levels unlike anything they have felt in years

Our 93% patient satisfaction rate on the 21-day program reflects consistent outcomes across conditions.

## Who Should Consider Panchkarma

- Anyone with chronic conditions that have not responded to conventional treatment
- Anyone who wants a systemic reset before or after a treatment protocol
- Anyone experiencing chronic fatigue, digestive sluggishness, or mental fog
- As a preventive annual detox for healthy individuals

Panchkarma is not for everyone in every season or state of health. A pre-program consultation is mandatory.
    `,
  },
  {
    slug: "diabetes-ayurveda-hba1c",
    category: "DIABETES",
    title:
      "How Ayurveda Approaches Type 2 Diabetes — and What HbA1c Results Show",
    excerpt:
      "Type 2 diabetes is a disease of metabolic dysfunction, not just high sugar. Ayurveda addresses the root — and the HbA1c numbers follow.",
    readTime: "5 min read",
    date: "February 2025",
    image:
      "https://images.unsplash.com/photo-1573497620053-ea5300f94f21?w=800&auto=format&fit=crop&q=80",
    tags: ["Diabetes", "HbA1c", "Metabolic Health", "Ayurveda"],
    content: `
## The Problem with How We Manage Diabetes

Modern medicine treats Type 2 diabetes primarily through glucose management — bringing numbers into range with medication. This is important. But it misses the mechanism.

Type 2 diabetes is fundamentally a disease of **insulin resistance** — cells refusing to respond to insulin. The blood sugar is a symptom. The insulin resistance is the disease.

Ayurveda understood this conceptually thousands of years before the term existed. In classical texts, Prameha (which encompasses metabolic disorders including diabetes) is described as a disease of excess — excess Ama, excess Kapha, excess in the channels — causing blockage and dysfunction at the cellular level.

The solution, therefore, is not just suppression. It is clearance.

## How Our Protocol Addresses Insulin Resistance

**Herbs that target cellular sensitivity:**
- **Vijaysar** (Pterocarpus marsupium) — shown in research to regenerate pancreatic beta cells
- **Gurmar** (Gymnema sylvestre) — the "sugar destroyer" — reduces glucose absorption and stimulates insulin secretion
- **Karela** (Bitter melon) — polypeptide-P mimics insulin at the receptor level
- **Methi** (Fenugreek) — slows glucose absorption and improves peripheral insulin sensitivity

These are not generic supplements. They are prescribed in specific formulations, at specific doses, for your specific constitution and current blood chemistry.

**Dietary correction:**
A diet plan calibrated to your Prakriti and glycaemic profile. Not generic "eat less sugar" advice — a precise plan that corrects Agni (digestive fire) and reduces Ama production at the source.

**Virechana (Panchkarma purgation):**
The metabolic toxins that block insulin receptors are cleared through therapeutic purgation. This is the detox layer that changes the cellular environment — and it consistently accelerates results in our diabetic patients.

## The Numbers: What Patients See

Across our documented patient base:
- Average **2.1 HbA1c point reduction** within 90 days
- **74%** of patients reduced oral medication dosage under physician supervision
- **89%** reported improved energy and reduced post-meal fatigue

The most dramatic case we document: HbA1c from 9.8 to 6.2 in 4 months — without insulin.

## The Timeline and What to Expect

- **Weeks 1–4:** Dietary changes and herbs begin. Energy and post-meal sluggishness improve.
- **Weeks 4–8:** Fasting and PP glucose begin to stabilise.
- **Month 3:** HbA1c test reflects cumulative improvement.
- **Month 4–6:** Medication tapering begins (always supervised by your physician).

## The Honest Caveat

Advanced diabetes with long-term insulin dependency, severe neuropathy, or end-organ damage requires sustained management. Reversal is harder in these cases — but meaningful improvement in glucose control, energy, and quality of life is consistently achievable.

The earlier you begin, the more room there is to work with.
    `,
  },
  {
    slug: "ayurveda-cancer-integrative",
    category: "CANCER CARE",
    title: "Integrative Ayurveda in Cancer Care: What It Can and Cannot Do",
    excerpt:
      "Ayurveda does not treat cancer. It treats the body experiencing cancer. Here is the honest, evidence-grounded answer to what integrative care achieves.",
    readTime: "7 min read",
    date: "January 2025",
    image:
      "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=800&auto=format&fit=crop&q=80",
    tags: ["Cancer", "Integrative Care", "Immunity", "Ayurveda"],
    content: `
## The Honest Starting Point

We will not claim Ayurveda cures cancer. It does not. Anyone who says otherwise is misleading you — and that misleading can cost lives.

What Ayurveda can do — and does, consistently, in our documented cases — is make the body stronger to endure and recover from cancer treatment. That is a meaningful, measurable, life-improving contribution.

## What Happens to the Body During Cancer Treatment

Chemotherapy, radiation, and surgery are powerful. They are also systemically destructive. The intended targets are cancer cells — but the collateral impact includes:
- Bone marrow suppression (low WBC, low platelet count)
- Severe fatigue and reduced quality of life
- Gastrointestinal disruption — nausea, mouth sores, appetite loss
- Immune compromise — increased infection risk
- Emotional and psychological exhaustion

These side effects are not inevitable to their full severity. The body's baseline resilience determines how much it suffers.

## What Ayurveda Targets in Cancer Care

**Immunity fortification — the core role:**
Ayurveda's Rasayana system is specifically designed to protect and rebuild Ojas — the essential vitality that governs immune competence. Herbs like Ashwagandha, Guduchi, Amalaki, and Shatavari have documented adaptogenic and immunomodulatory properties.

When Ojas is strong, the body tolerates treatment better. Blood counts hold. Recovery between cycles is faster.

**Side effect management:**
- Nausea: Shunthi (ginger), Ela (cardamom) formulations
- Mouth sores: Yashtimadhu (licorice) preparations
- Fatigue: Ashwagandha + Shatavari combination protocols
- Appetite: Agni-stimulating formulations

**Post-treatment restoration:**
After cancer treatment ends, the body is depleted. Panchkarma, timed appropriately, provides the deepest systemic reset — clearing treatment residue and rebuilding from the cleared foundation.

## What Our Patients Report

Across 5+ years of integrative cancer support:
- **70%** reported significant reduction in chemotherapy side effects
- **82%** showed improved energy and immunity scores during treatment
- Most common feedback: "My oncologist was surprised at how well I was tolerating treatment."

## The Safety Question

Every herb we prescribe is reviewed for oncology compatibility. Some herbs — particularly blood thinners or CYP450 enzyme inducers — can interfere with chemotherapy. This is not a trivial concern.

Our protocols are designed with full awareness of your oncology medications. We work alongside your oncology team, not in opposition to it.

## Who Should Consider Integrative Ayurvedic Support

- Anyone beginning chemotherapy or radiation who wants to build resilience first
- Anyone mid-treatment experiencing significant side effects
- Anyone in post-treatment recovery seeking systemic restoration
- Anyone in remission wanting to build long-term immune health

The conversation should start early — not as a last resort.
    `,
  },
];

export function getPostBySlug(slug: string): BlogPost | undefined {
  return posts.find((p) => p.slug === slug);
}

export function getAllPostSlugs(): string[] {
  return posts.map((p) => p.slug);
}
